name: notion
description: A starting point for Dart libraries or applications.
version: 1.0.4
homepage: https://github.com/berkobob/notion
publish_to: none

environment:
  sdk: '>=2.18.4 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  http: ^0.13.5
  logger:
    git:
      url: https://github.com/berkobob/logger
      ref: main
